# Generated by Django 3.2.18 on 2024-09-08 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modalidade', models.CharField(choices=[('Basquete', 'Basquete'), ('Futsal', 'Futsal'), ('Handebol', 'Handebol'), ('Vôlei', 'Vôlei'), ('Atletismo', 'Atletismo')], max_length=50)),
                ('curso', models.CharField(choices=[('ADM', 'Administração'), ('ADM_PUB', 'Administração Pública'), ('AGR', 'Agronomia'), ('BIO', 'Biologia'), ('BIB', 'Biblioteconomia'), ('COMP', 'Ciência da Computação'), ('CONT', 'Ciências Contábeis'), ('DES', 'Design'), ('ENG_CIV', 'Engenharia Civil'), ('ENG_MAT', 'Engenharia de Materiais'), ('FILO', 'Filosofia'), ('FIS', 'Física'), ('JOR', 'Jornalismo'), ('LET_LIB', 'Letras - Libras'), ('MAT', 'Matemática'), ('MAT_COMP', 'Matemática Computacional'), ('MED', 'Medicina'), ('VET', 'Medicina Veterinária'), ('MUS', 'Música'), ('QUI', 'Química')], max_length=50)),
                ('data_inicio_bolsa', models.DateField()),
                ('data_fim_bolsa', models.DateField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=50)),
                ('competidor', models.BooleanField(default=False)),
                ('carga_horaria', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('curso', models.CharField(choices=[('ADM', 'Administração'), ('ADM_PUB', 'Administração Pública'), ('AGR', 'Agronomia'), ('BIO', 'Biologia'), ('BIB', 'Biblioteconomia'), ('COMP', 'Ciência da Computação'), ('CONT', 'Ciências Contábeis'), ('DES', 'Design'), ('ENG_CIV', 'Engenharia Civil'), ('ENG_MAT', 'Engenharia de Materiais'), ('FILO', 'Filosofia'), ('FIS', 'Física'), ('JOR', 'Jornalismo'), ('LET_LIB', 'Letras - Libras'), ('MAT', 'Matemática'), ('MAT_COMP', 'Matemática Computacional'), ('MED', 'Medicina'), ('VET', 'Medicina Veterinária'), ('MUS', 'Música'), ('QUI', 'Química')], max_length=50)),
                ('semestre', models.IntegerField()),
                ('modalidade', models.CharField(choices=[('Basquete', 'Basquete'), ('Futsal', 'Futsal'), ('Handebol', 'Handebol'), ('Vôlei', 'Vôlei'), ('Atletismo', 'Atletismo')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=50)),
                ('frequencia_entregue', models.BooleanField(default=False)),
                ('frequencia_participantes_entregue', models.BooleanField(default=False)),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.bolsista')),
            ],
        ),
    ]
